export const projectTags: string[] = [
  'E-commerce',
  'Web App',
  'Angular',
  'Mobile App',
  'Fitness',
  'React Native',
  'Education',
  'AI',
  'Language',
  'Management',
  'Machine Learning',
  'Finance',
  'Automation',
  'Messaging',
  'Real-time',
  'Marketplace',
  'Security',
  'File Transfer',
  'Weather',
  'Forecasting',
];
