import { Filter } from '@shared/types/filters.types';

export const AVAILABLE_PROJECT_TAGS: Filter[] = [
  { value: 'ai', viewValue: 'AI' },
  { value: 'machine-learning', viewValue: 'Machine Learning' },
  { value: 'data-science', viewValue: 'Data Science' },
  { value: 'blockchain', viewValue: 'Blockchain' },
  { value: 'cybersecurity', viewValue: 'Cybersecurity' },
  { value: 'biotechnology', viewValue: 'Biotechnology' },
  { value: 'genetics', viewValue: 'Genetics' },
  { value: 'physics', viewValue: 'Physics' },
  { value: 'chemistry', viewValue: 'Chemistry' },
  { value: 'astronomy', viewValue: 'Astronomy' },
  { value: 'robotics', viewValue: 'Robotics' },
  { value: 'automation', viewValue: 'Automation' },
  { value: 'iot', viewValue: 'IoT (Internet of Things)' },
  { value: 'renewable-energy', viewValue: 'Renewable Energy' },
  { value: 'material-science', viewValue: 'Material Science' },
  { value: 'philosophy', viewValue: 'Philosophy' },
  { value: 'psychology', viewValue: 'Psychology' },
  { value: 'sociology', viewValue: 'Sociology' },
  { value: 'economics', viewValue: 'Economics' },
  { value: 'education', viewValue: 'Education' },
  { value: 'public-health', viewValue: 'Public Health' },
  { value: 'neuroscience', viewValue: 'Neuroscience' },
  { value: 'pharmacology', viewValue: 'Pharmacology' },
  { value: 'nutrition', viewValue: 'Nutrition' },
  { value: 'epidemiology', viewValue: 'Epidemiology' },
  { value: 'climate-change', viewValue: 'Climate Change' },
  { value: 'ecology', viewValue: 'Ecology' },
  { value: 'sustainability', viewValue: 'Sustainability' },
  {
    value: 'environmental-engineering',
    viewValue: 'Environmental Engineering',
  },
  { value: 'geology', viewValue: 'Geology' },
  { value: 'ethics', viewValue: 'Ethics' },
  { value: 'policy', viewValue: 'Policy' },
  { value: 'history', viewValue: 'History' },
  { value: 'mathematics', viewValue: 'Mathematics' },
  { value: 'statistics', viewValue: 'Statistics' },
];
