import {
  DashboardRecentProjectItem,
  DashboardRecentProjectItemModal,
} from '../src/app/shared/types/dashboard.types';

export const recentProjectContent: DashboardRecentProjectItem[] = [
  {
    id: 1,
    projectTitle: 'E-Shop Platform',
    deadline: '30.12',
    statusProgress: 'In Progress',
    progress: 50,
    assignedTeamMembers: ['DM', 'AC', 'JS'],
  },
  {
    id: 2,
    projectTitle: 'Mobile App Development',
    deadline: '15.01',
    statusProgress: 'In Progress',
    progress: 45,
    assignedTeamMembers: ['MK', 'RP'],
  },
  {
    id: 3,
    projectTitle: 'Language Learning Platform',
    deadline: '25.02',
    statusProgress: 'In Progress',
    progress: 40,
    assignedTeamMembers: ['DM', 'KS', 'AT'],
  },
  {
    id: 4,
    projectTitle: 'Student Management System',
    deadline: '10.03',
    statusProgress: 'Completed',
    progress: 100,
    assignedTeamMembers: ['LM', 'DM'],
  },
  {
    id: 5,
    projectTitle: 'AI Assistant for E-commerce',
    deadline: '05.01',
    statusProgress: 'In Progress',
    progress: 60,
    assignedTeamMembers: ['AC', 'DM', 'RP'],
  },
  {
    id: 6,
    projectTitle: 'Automated Financial Tracker',
    deadline: '20.01',
    statusProgress: 'In Progress',
    progress: 35,
    assignedTeamMembers: ['DM', 'SB'],
  },
  {
    id: 7,
    projectTitle: 'Real-time Messaging App',
    deadline: '28.02',
    statusProgress: 'In Progress',
    progress: 80,
    assignedTeamMembers: ['JS', 'AC'],
  },
  {
    id: 8,
    projectTitle: 'Online Course Marketplace',
    deadline: '12.01',
    statusProgress: 'In Progress',
    progress: 50,
    assignedTeamMembers: ['MK', 'RP', 'DM'],
  },
  {
    id: 9,
    projectTitle: 'Secure File Transfer System',
    deadline: '08.02',
    statusProgress: 'In Progress',
    progress: 70,
    assignedTeamMembers: ['AT', 'LM'],
  },
  {
    id: 10,
    projectTitle: 'Weather Forecasting App',
    deadline: '18.01',
    statusProgress: 'Completed',
    progress: 100,
    assignedTeamMembers: ['RP', 'SB'],
  },
];

export const recentProjectModalContent: DashboardRecentProjectItemModal[] = [
  {
    id: 1,
    projectTitle: 'E-Shop Platform',
    deadline: '30.12',
    statusProgress: 'In Progress',
    progress: 50,
    assignedTeamMembers: ['DM', 'AC', 'JS'],
    shortDescription:
      'A platform to enhance online shopping with a user-friendly interface and secure payment integration.',
    priorityLevel: 'High',
    creationDate: '01.10',
    lastUpdated: '20.12',
    tags: ['E-commerce', 'Web App', 'Angular'],
    contact: {
      name: 'John Doe',
      email: 'johndoe@example.com',
    },
    files: ['design-doc.pdf', 'requirements.xlsx'],
  },
  {
    id: 2,
    projectTitle: 'Mobile App Development',
    deadline: '15.01',
    statusProgress: 'In Progress',
    progress: 45,
    assignedTeamMembers: ['MK', 'RP'],
    shortDescription:
      'Development of a cross-platform mobile application for fitness tracking.',
    priorityLevel: 'Medium',
    creationDate: '15.09',
    lastUpdated: '18.12',
    tags: ['Mobile App', 'Fitness', 'React Native'],
    contact: {
      name: 'Jane Smith',
      email: 'janesmith@example.com',
    },
    files: ['app-mockups.zip', 'specifications.pdf'],
  },
  {
    id: 3,
    projectTitle: 'Language Learning Platform',
    deadline: '25.02',
    statusProgress: 'In Progress',
    progress: 40,
    assignedTeamMembers: ['DM', 'KS', 'AT'],
    shortDescription:
      'A platform for language exchange and learning with AI-powered assistance.',
    priorityLevel: 'High',
    creationDate: '10.11',
    lastUpdated: '15.12',
    tags: ['Education', 'AI', 'Language'],
    contact: {
      name: 'Alice Brown',
      email: 'alicebrown@example.com',
    },
    files: ['concept-outline.docx', 'language-data.csv'],
  },
  {
    id: 4,
    projectTitle: 'Student Management System',
    deadline: '10.03',
    statusProgress: 'Completed',
    progress: 100,
    assignedTeamMembers: ['LM', 'DM'],
    shortDescription:
      'A system for managing student projects, tasks, and performance reviews.',
    priorityLevel: 'Medium',
    creationDate: '05.07',
    lastUpdated: '01.12',
    tags: ['Education', 'Management', 'Web App'],
    contact: {
      name: 'Chris Evans',
      email: 'chrisevans@example.com',
    },
    files: ['final-report.pdf', 'task-list.xlsx'],
  },
  {
    id: 5,
    projectTitle: 'AI Assistant for E-commerce',
    deadline: '05.01',
    statusProgress: 'In Progress',
    progress: 60,
    assignedTeamMembers: ['AC', 'DM', 'RP'],
    shortDescription:
      'An AI assistant to improve product recommendations and user engagement.',
    priorityLevel: 'High',
    creationDate: '01.08',
    lastUpdated: '18.12',
    tags: ['AI', 'E-commerce', 'Machine Learning'],
    contact: {
      name: 'Sophia Lee',
      email: 'sophialee@example.com',
    },
    files: ['ai-model-specs.pdf', 'training-data.zip'],
  },
  {
    id: 6,
    projectTitle: 'Automated Financial Tracker',
    deadline: '20.01',
    statusProgress: 'In Progress',
    progress: 35,
    assignedTeamMembers: ['DM', 'SB'],
    shortDescription:
      'A financial tracking app with automated expense categorization and analysis.',
    priorityLevel: 'Medium',
    creationDate: '20.09',
    lastUpdated: '12.12',
    tags: ['Finance', 'Automation', 'Mobile App'],
    contact: {
      name: 'Emily Carter',
      email: 'emilycarter@example.com',
    },
    files: ['prototype.pptx', 'expense-data.xlsx'],
  },
  {
    id: 7,
    projectTitle: 'Real-time Messaging App',
    deadline: '28.02',
    statusProgress: 'In Progress',
    progress: 80,
    assignedTeamMembers: ['JS', 'AC'],
    shortDescription:
      'A real-time messaging application with end-to-end encryption.',
    priorityLevel: 'High',
    creationDate: '10.10',
    lastUpdated: '22.12',
    tags: ['Messaging', 'Real-time', 'Mobile App'],
    contact: {
      name: 'Michael Johnson',
      email: 'michaeljohnson@example.com',
    },
    files: ['encryption-guide.pdf', 'feature-list.docx'],
  },
  {
    id: 8,
    projectTitle: 'Online Course Marketplace',
    deadline: '12.01',
    statusProgress: 'In Progress',
    progress: 50,
    assignedTeamMembers: ['MK', 'RP', 'DM'],
    shortDescription: 'A platform for users to buy and sell online courses.',
    priorityLevel: 'Medium',
    creationDate: '01.11',
    lastUpdated: '15.12',
    tags: ['Education', 'Marketplace', 'Web App'],
    contact: {
      name: 'Rachel Green',
      email: 'rachelgreen@example.com',
    },
    files: ['course-market-analysis.pdf', 'ui-design.psd'],
  },
  {
    id: 9,
    projectTitle: 'Secure File Transfer System',
    deadline: '08.02',
    statusProgress: 'In Progress',
    progress: 70,
    assignedTeamMembers: ['AT', 'LM'],
    shortDescription:
      'A secure system for transferring sensitive files with authentication mechanisms.',
    priorityLevel: 'High',
    creationDate: '15.10',
    lastUpdated: '20.12',
    tags: ['Security', 'File Transfer', 'Web App'],
    contact: {
      name: 'Tony Stark',
      email: 'tonystark@example.com',
    },
    files: ['security-audit.pdf', 'transfer-protocol.docx'],
  },
  {
    id: 10,
    projectTitle: 'Weather Forecasting App',
    deadline: '18.01',
    statusProgress: 'Completed',
    progress: 100,
    assignedTeamMembers: ['RP', 'SB'],
    shortDescription:
      'An app providing real-time weather updates and forecasts.',
    priorityLevel: 'Low',
    creationDate: '01.06',
    lastUpdated: '01.12',
    tags: ['Weather', 'Forecasting', 'Mobile App'],
    contact: {
      name: 'Bruce Wayne',
      email: 'brucewayne@example.com',
    },
    files: ['weather-api-docs.pdf', 'forecast-algorithm.py'],
  },
];
