import { IUser } from '@shared/types/users.types';

export const usersContent: IUser[] = [
  {
    id: '1',
    username: 'Dr. Alice Smith',
    avatarUrl:
      'https://upload.wikimedia.org/wikipedia/commons/7/71/Ewa_Zajączkowska-Hernik%2C_18.07.24_%2801%29.jpg',
    role: 'Researcher',
    affiliation: 'Physics Department, XYZ University',
    email: 'alice.smith@xyz.edu',
    phone: '+1234567890',
    publicationCount: 7,
    patentCount: 0,
    researchCount: 3,
    lastActive: '2024-12-20T14:45:00Z',
    status: 'Active',
    tags: ['Team Lead', 'Editor'],
    dateOfBirth: '1980-03-14',
    userType: 'student',
    universityGroup: 'PI-211',
  },
  {
    id: '2',
    username: 'John Doe',
    avatarUrl:
      'https://yt3.googleusercontent.com/aYMfqtZoi7h8dKN0H626KsxrwGyver5V0t_8voqHaMW6k_WApCwj3vxfSQs41vJZh-ugiMfcbQ=s900-c-k-c0x00ffffff-no-rj',
    role: 'Administrator',
    affiliation: 'Central Admin, XYZ University',
    email: 'john.doe@xyz.edu',
    phone: '+0987654321',
    publicationCount: 7,
    patentCount: 0,
    researchCount: 3,
    lastActive: '2024-12-18T09:30:00Z',
    status: 'Active',
    tags: ['Admin'],
    dateOfBirth: '1975-06-22',
    userType: 'student',
    universityGroup: 'PI-211',
  },
  {
    id: '3',
    username: 'Dr. Emily Brown',
    avatarUrl:
      'https://i.ytimg.com/vi/D9gWp9gbaEg/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLB_s2yzRWmT3q9sukyyjo3KrvHlSQ',
    role: 'Researcher',
    affiliation: 'Biology Department, ABC Institute',
    email: 'emily.brown@abc.org',
    phone: '+1239876543',
    publicationCount: 7,
    patentCount: 0,
    researchCount: 3,
    lastActive: '2024-12-19T17:00:00Z',
    status: 'Pending',
    tags: ['Reviewer'],
    dateOfBirth: '1983-11-07',
    userType: 'student',
    universityGroup: 'PI-211',
  },
  {
    id: '4',
    username: 'Michael Lee',
    avatarUrl:
      'https://i.gremicdn.pl/image/free/c5ac7ed6b8397236705c2f2560890ae9/?t=crop:2204:1366:nowe:50.705467372134:215.41093474427,resize:fill:948:593,enlarge:1',
    role: 'Student',
    affiliation: 'Computer Science Department, XYZ University',
    email: 'michael.lee@xyz.edu',
    phone: '+4561237890',
    publicationCount: 7,
    patentCount: 0,
    researchCount: 3,
    lastActive: '2024-12-21T12:00:00Z',
    status: 'Inactive',
    tags: ['Contributor'],
    dateOfBirth: '2001-01-10',
    userType: 'student',
    universityGroup: 'PI-211',
  },
  {
    id: '5',
    username: 'Dr. Sarah Wilson',
    avatarUrl:
      'https://bi.im-g.pl/im/7e/dd/1c/z30267262ICR,Sanah-podczas-koncertu-na-Stadionie-Slaskim-w-Chor.jpg',
    role: 'Researcher',
    affiliation: 'Engineering Department, DEF Institute',
    email: 'sarah.wilson@def.edu',
    phone: '+7891234560',
    publicationCount: 7,
    patentCount: 0,
    researchCount: 3,
    lastActive: '2024-12-22T10:15:00Z',
    status: 'Active',
    tags: ['Team Lead', 'Expert'],
    dateOfBirth: '1978-08-30',
    userType: 'student',
    universityGroup: 'PI-211',
  },
  {
    id: '6',
    username: 'Dr. Laura Thompson',
    avatarUrl:
      'https://yt3.googleusercontent.com/ORAuTRcDsufrp_XCSTDK7dewCU1CHoaiG3QGHpRiwzIM-0epGN7XXuRnj3tGWuCmAgg7A9sFfg=s900-c-k-c0x00ffffff-no-rj',
    role: 'Researcher',
    affiliation: 'Mathematics Department, LMN University',
    email: 'laura.thompson@lmn.edu',
    phone: '+1236547890',
    publicationCount: 7,
    patentCount: 0,
    researchCount: 3,
    lastActive: '2024-12-23T16:45:00Z',
    status: 'Active',
    tags: ['Mathematician', 'Reviewer'],
    dateOfBirth: '1985-05-05',
    userType: 'student',
    universityGroup: 'PI-211',
  },
  {
    id: '7',
    username: 'Dr. William Harris',
    avatarUrl: 'https://wnet.fm/wp-content/uploads/2023/08/IMG_1160.jpg',
    role: 'Researcher',
    affiliation: 'Environmental Science, Green Institute',
    email: 'william.harris@green.org',
    phone: '+9871234567',
    publicationCount: 7,
    patentCount: 0,
    researchCount: 3,
    lastActive: '2024-12-22T11:30:00Z',
    status: 'Pending',
    tags: ['Team Lead', 'Ecologist'],
    dateOfBirth: '1972-12-03',
    userType: 'student',
    universityGroup: 'PI-211',
  },
  {
    id: '8',
    username: 'Sophia Martinez',
    avatarUrl:
      'https://yt3.googleusercontent.com/u5OB7mpDktPkbTVjc8Rssx71RPH4akdyHPNONilfvGBWCg9T7kMS-iV3JTAss5FZn_k7hd7H=s900-c-k-c0x00ffffff-no-rj',
    role: 'Student',
    affiliation: 'Chemistry Department, LMN University',
    email: 'sophia.martinez@lmn.edu',
    phone: '+6547891230',
    publicationCount: 7,
    patentCount: 0,
    researchCount: 3,
    lastActive: '2024-12-20T15:20:00Z',
    status: 'Active',
    tags: ['Assistant', 'Contributor'],
    dateOfBirth: '2002-07-18',
    userType: 'student',
    universityGroup: 'PI-211',
  },
  {
    id: '9',
    username: 'Dr. James Wilson',
    avatarUrl:
      'https://yt3.googleusercontent.com/loheQn5VW2zuvJi64keZKe4ogBX2vGUAUfic2_J4cTj6UO8PHCyANBkZIp9RVRTw2qSMVNClMHk=s900-c-k-c0x00ffffff-no-rj',
    role: 'Administrator',
    affiliation: 'Central Office, Green Institute',
    email: 'james.wilson@green.org',
    phone: '+1239876541',
    publicationCount: 7,
    patentCount: 0,
    researchCount: 3,
    lastActive: '2024-12-21T14:10:00Z',
    status: 'Active',
    tags: ['Admin', 'Coordinator'],
    dateOfBirth: '1969-04-11',
    userType: 'student',
    universityGroup: 'PI-211',
  },
  {
    id: '10',
    username: 'Emma Johnson',
    avatarUrl:
      'https://yt3.googleusercontent.com/uKVX93BZk6SUi5hwF6F9oW6LBs0NVTd1hf6Ux1IFiRwzx0x-WI9xgvuEsAo4oIQsweBX14zTvg=s900-c-k-c0x00ffffff-no-rj',
    role: 'Researcher',
    affiliation: 'Astronomy Department, XYZ University',
    email: 'emma.johnson@xyz.edu',
    phone: '+4569873210',
    publicationCount: 7,
    patentCount: 0,
    researchCount: 3,
    lastActive: '2024-12-22T18:40:00Z',
    status: 'Inactive',
    tags: ['Astrophysicist', 'Data Analyst'],
    dateOfBirth: '1986-09-12',
    userType: 'student',
    universityGroup: 'PI-211',
  },
  {
    id: '11',
    username: 'Dr. Olivia White',
    avatarUrl:
      'https://api.culture.pl/sites/default/files/styles/1920_auto/public/2019-09/dawid_podsiadlo_promo-2.jpg?itok=x4cbs9aq',
    role: 'Researcher',
    affiliation: 'Biotechnology Department, ABC Institute',
    email: 'olivia.white@abc.org',
    phone: '+7894561230',
    publicationCount: 7,
    patentCount: 0,
    researchCount: 3,
    lastActive: '2024-12-19T10:30:00Z',
    status: 'Active',
    tags: ['Biotechnologist', 'Innovator'],
    dateOfBirth: '1982-03-02',
    userType: 'student',
    universityGroup: 'PI-211',
  },
  {
    id: '12',
    username: 'Dr. Ethan Walker',
    avatarUrl:
      'https://preview.redd.it/who-should-be-blamed-for-robert-lewandowski-lack-of-form-v0-q2juliey3egc1.jpeg?width=640&crop=smart&auto=webp&s=1adb74a1c4a3ab893a6a3b0bacd906f263ea12ed',
    role: 'Senior Scientist',
    affiliation: 'Physics Department, National Science Center',
    email: 'ethan.walker@nsc.gov',
    phone: '+3216549870',
    publicationCount: 7,
    patentCount: 0,
    researchCount: 3,
    lastActive: '2024-12-18T13:15:00Z',
    status: 'Active',
    tags: ['Physicist', 'Team Lead'],
    dateOfBirth: '1970-10-05',
    userType: 'student',
    universityGroup: 'PI-211',
  },
  {
    id: '13',
    username: 'Ava Smith',
    avatarUrl:
      'https://yt3.googleusercontent.com/ytc/AIdro_kvdxAg2dZbgnADkHp6oR8KdOVRY09RdYNM-MCBzM8Ruw=s900-c-k-c0x00ffffff-no-rj',
    role: 'Graduate Student',
    affiliation: 'Computer Science Department, LMN University',
    email: 'ava.smith@lmn.edu',
    phone: '+6543217890',
    publicationCount: 7,
    patentCount: 0,
    researchCount: 3,
    lastActive: '2024-12-20T09:45:00Z',
    status: 'Active',
    tags: ['Programmer', 'AI Enthusiast'],
    dateOfBirth: '1999-02-20',
    userType: 'student',
    universityGroup: 'PI-211',
  },
  {
    id: '14',
    username: 'Dr. Noah Martinez',
    avatarUrl:
      'https://modawysoka.pl/wp-content/uploads/2025/01/dzieki-400x400.jpg',
    role: 'Postdoc Researcher',
    affiliation: 'Astronomy Department, XYZ University',
    email: 'noah.martinez@xyz.edu',
    phone: '+4561237890',
    publicationCount: 7,
    patentCount: 0,
    researchCount: 3,
    lastActive: '2024-12-17T11:20:00Z',
    status: 'Pending',
    tags: ['Researcher', 'Data Scientist'],
    dateOfBirth: '1990-12-15',
    userType: 'student',
    universityGroup: 'PI-211',
  },
  {
    id: '15',
    username: 'Mia Brown',
    avatarUrl:
      'https://visitwroclaw.eu/files/news/visitwro_daria-zawialow-albo-inaczej.jpeg',
    role: 'Research Assistant',
    affiliation: 'Environmental Science, Green Institute',
    email: 'mia.brown@green.org',
    phone: '+7891234560',
    publicationCount: 7,
    patentCount: 0,
    researchCount: 3,
    lastActive: '2024-12-16T14:50:00Z',
    status: 'Active',
    tags: ['Ecologist', 'Field Expert'],
    dateOfBirth: '1996-08-08',
    userType: 'student',
    universityGroup: 'PI-211',
  },
];
